// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: helloworld.proto

package tgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_Get    Method = 0
	Method_Post   Method = 1
	Method_Delete Method = 2
	Method_Patch  Method = 3
)

var Method_name = map[int32]string{
	0: "Get",
	1: "Post",
	2: "Delete",
	3: "Patch",
}

var Method_value = map[string]int32{
	"Get":    0,
	"Post":   1,
	"Delete": 2,
	"Patch":  3,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}

func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

type HeartbeatRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}
func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type HeartbeatResponse struct {
	Code                 int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Method               Method                        `protobuf:"varint,3,opt,name=method,proto3,enum=tgrpc.Method" json:"method,omitempty"`
	Data                 *HeartbeatResponse_DataStruct `protobuf:"bytes,50,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}
func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HeartbeatResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HeartbeatResponse) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_Get
}

func (m *HeartbeatResponse) GetData() *HeartbeatResponse_DataStruct {
	if m != nil {
		return m.Data
	}
	return nil
}

type HeartbeatResponse_DataStruct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse_DataStruct) Reset()         { *m = HeartbeatResponse_DataStruct{} }
func (m *HeartbeatResponse_DataStruct) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse_DataStruct) ProtoMessage()    {}
func (*HeartbeatResponse_DataStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1, 0}
}
func (m *HeartbeatResponse_DataStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse_DataStruct.Unmarshal(m, b)
}
func (m *HeartbeatResponse_DataStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse_DataStruct.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse_DataStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse_DataStruct.Merge(m, src)
}
func (m *HeartbeatResponse_DataStruct) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse_DataStruct.Size(m)
}
func (m *HeartbeatResponse_DataStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse_DataStruct.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse_DataStruct proto.InternalMessageInfo

func (m *HeartbeatResponse_DataStruct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Handler1Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Left                 int64    `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	Right                int64    `protobuf:"varint,3,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler1Request) Reset()         { *m = Handler1Request{} }
func (m *Handler1Request) String() string { return proto.CompactTextString(m) }
func (*Handler1Request) ProtoMessage()    {}
func (*Handler1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}
func (m *Handler1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler1Request.Unmarshal(m, b)
}
func (m *Handler1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler1Request.Marshal(b, m, deterministic)
}
func (m *Handler1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler1Request.Merge(m, src)
}
func (m *Handler1Request) XXX_Size() int {
	return xxx_messageInfo_Handler1Request.Size(m)
}
func (m *Handler1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler1Request.DiscardUnknown(m)
}

var xxx_messageInfo_Handler1Request proto.InternalMessageInfo

func (m *Handler1Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Handler1Request) GetLeft() int64 {
	if m != nil {
		return m.Left
	}
	return 0
}

func (m *Handler1Request) GetRight() int64 {
	if m != nil {
		return m.Right
	}
	return 0
}

type Handler1Response struct {
	Code                 int32                        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Method               Method                       `protobuf:"varint,3,opt,name=method,proto3,enum=tgrpc.Method" json:"method,omitempty"`
	Data                 *Handler1Response_DataStruct `protobuf:"bytes,50,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Handler1Response) Reset()         { *m = Handler1Response{} }
func (m *Handler1Response) String() string { return proto.CompactTextString(m) }
func (*Handler1Response) ProtoMessage()    {}
func (*Handler1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}
func (m *Handler1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler1Response.Unmarshal(m, b)
}
func (m *Handler1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler1Response.Marshal(b, m, deterministic)
}
func (m *Handler1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler1Response.Merge(m, src)
}
func (m *Handler1Response) XXX_Size() int {
	return xxx_messageInfo_Handler1Response.Size(m)
}
func (m *Handler1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler1Response.DiscardUnknown(m)
}

var xxx_messageInfo_Handler1Response proto.InternalMessageInfo

func (m *Handler1Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Handler1Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Handler1Response) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_Get
}

func (m *Handler1Response) GetData() *Handler1Response_DataStruct {
	if m != nil {
		return m.Data
	}
	return nil
}

type Handler1Response_DataStruct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               int64    `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler1Response_DataStruct) Reset()         { *m = Handler1Response_DataStruct{} }
func (m *Handler1Response_DataStruct) String() string { return proto.CompactTextString(m) }
func (*Handler1Response_DataStruct) ProtoMessage()    {}
func (*Handler1Response_DataStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3, 0}
}
func (m *Handler1Response_DataStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler1Response_DataStruct.Unmarshal(m, b)
}
func (m *Handler1Response_DataStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler1Response_DataStruct.Marshal(b, m, deterministic)
}
func (m *Handler1Response_DataStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler1Response_DataStruct.Merge(m, src)
}
func (m *Handler1Response_DataStruct) XXX_Size() int {
	return xxx_messageInfo_Handler1Response_DataStruct.Size(m)
}
func (m *Handler1Response_DataStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler1Response_DataStruct.DiscardUnknown(m)
}

var xxx_messageInfo_Handler1Response_DataStruct proto.InternalMessageInfo

func (m *Handler1Response_DataStruct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Handler1Response_DataStruct) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("tgrpc.Method", Method_name, Method_value)
	proto.RegisterType((*HeartbeatRequest)(nil), "tgrpc.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "tgrpc.HeartbeatResponse")
	proto.RegisterType((*HeartbeatResponse_DataStruct)(nil), "tgrpc.HeartbeatResponse.DataStruct")
	proto.RegisterType((*Handler1Request)(nil), "tgrpc.Handler1Request")
	proto.RegisterType((*Handler1Response)(nil), "tgrpc.Handler1Response")
	proto.RegisterType((*Handler1Response_DataStruct)(nil), "tgrpc.Handler1Response.DataStruct")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xd1, 0x6a, 0xe2, 0x50,
	0x10, 0x86, 0x3d, 0x89, 0x89, 0x3a, 0xcb, 0xba, 0xd9, 0x61, 0xd1, 0x20, 0x7b, 0x21, 0x59, 0x16,
	0xa4, 0x17, 0x81, 0xa6, 0xa5, 0xbd, 0x2a, 0xf4, 0x42, 0xa8, 0x50, 0x04, 0x89, 0x4f, 0x70, 0x4c,
	0xa6, 0x46, 0x88, 0x1e, 0x7b, 0x32, 0xb6, 0xf4, 0x19, 0xfa, 0x50, 0x7d, 0x8a, 0xbe, 0x4f, 0xe9,
	0xd1, 0xd4, 0xb6, 0xc1, 0xde, 0xf5, 0x6e, 0x66, 0x32, 0x93, 0x7f, 0xfe, 0x6f, 0x0e, 0x78, 0x19,
	0xe5, 0xb9, 0xba, 0x57, 0x3a, 0x4f, 0xc3, 0xb5, 0x56, 0xac, 0xd0, 0xe1, 0xb9, 0x5e, 0x27, 0x41,
	0x00, 0xde, 0x88, 0xa4, 0xe6, 0x19, 0x49, 0x8e, 0xe9, 0x76, 0x43, 0x05, 0x63, 0x1b, 0xac, 0x45,
	0xea, 0x8b, 0xbe, 0x18, 0xb4, 0x62, 0x6b, 0x91, 0x06, 0x4f, 0x02, 0x7e, 0xbf, 0x6b, 0x2a, 0xd6,
	0x6a, 0x55, 0x10, 0x22, 0xd4, 0x13, 0x95, 0x92, 0xe9, 0x73, 0x62, 0x13, 0xa3, 0x0f, 0x8d, 0x25,
	0x15, 0x85, 0x9c, 0x93, 0x6f, 0x99, 0xf1, 0x32, 0xc5, 0xff, 0xe0, 0x2e, 0x89, 0x33, 0x95, 0xfa,
	0x76, 0x5f, 0x0c, 0xda, 0xd1, 0xcf, 0xd0, 0xe8, 0x87, 0x63, 0x53, 0x8c, 0x77, 0x1f, 0xf1, 0x1c,
	0xea, 0xa9, 0x64, 0xe9, 0x47, 0x7d, 0x31, 0xf8, 0x11, 0xfd, 0xdb, 0x35, 0x55, 0xc4, 0xc3, 0xa1,
	0x64, 0x39, 0x65, 0xbd, 0x49, 0x38, 0x36, 0x03, 0xbd, 0xbf, 0x00, 0xfb, 0x5a, 0xc5, 0xc1, 0x35,
	0xfc, 0x1a, 0xc9, 0x55, 0x9a, 0x93, 0x3e, 0x3e, 0x60, 0xf2, 0xd5, 0x4e, 0x4e, 0x37, 0x6c, 0xf6,
	0xb6, 0x63, 0x13, 0xe3, 0x1f, 0x70, 0xf4, 0x62, 0x9e, 0xb1, 0xd9, 0xd9, 0x8e, 0xb7, 0x49, 0xf0,
	0x2c, 0xc0, 0xdb, 0xff, 0xed, 0x3b, 0x69, 0x9c, 0x7d, 0xa0, 0x11, 0x94, 0x34, 0x3e, 0x69, 0x57,
	0x61, 0x9c, 0x7e, 0x05, 0x03, 0x3b, 0xe0, 0x6a, 0x2a, 0x36, 0x79, 0xe9, 0x75, 0x97, 0x1d, 0x45,
	0xe0, 0x6e, 0xf5, 0xb1, 0x01, 0xf6, 0x15, 0xb1, 0x57, 0xc3, 0x26, 0xd4, 0x27, 0xaa, 0x60, 0x4f,
	0x20, 0x80, 0x3b, 0xa4, 0x9c, 0x98, 0x3c, 0x0b, 0x5b, 0xe0, 0x4c, 0x24, 0x27, 0x99, 0x67, 0x47,
	0x8f, 0x02, 0x9a, 0xe3, 0x87, 0x29, 0xe9, 0x3b, 0xd2, 0x78, 0x09, 0xad, 0xb7, 0x4b, 0x61, 0xb7,
	0x7a, 0x3b, 0x03, 0xbe, 0xe7, 0x1f, 0x3a, 0x6a, 0x50, 0xc3, 0x0b, 0x68, 0x96, 0xee, 0xb0, 0x53,
	0xb1, 0xbb, 0x9d, 0xef, 0x1e, 0xc0, 0x10, 0xd4, 0x66, 0xae, 0x79, 0xda, 0x27, 0x2f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xde, 0xe1, 0xde, 0x9b, 0xee, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyServerClient is the client API for MyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyServerClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Handler1(ctx context.Context, in *Handler1Request, opts ...grpc.CallOption) (*Handler1Response, error)
}

type myServerClient struct {
	cc *grpc.ClientConn
}

func NewMyServerClient(cc *grpc.ClientConn) MyServerClient {
	return &myServerClient{cc}
}

func (c *myServerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/tgrpc.MyServer/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myServerClient) Handler1(ctx context.Context, in *Handler1Request, opts ...grpc.CallOption) (*Handler1Response, error) {
	out := new(Handler1Response)
	err := c.cc.Invoke(ctx, "/tgrpc.MyServer/Handler1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyServerServer is the server API for MyServer service.
type MyServerServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Handler1(context.Context, *Handler1Request) (*Handler1Response, error)
}

func RegisterMyServerServer(s *grpc.Server, srv MyServerServer) {
	s.RegisterService(&_MyServer_serviceDesc, srv)
}

func _MyServer_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tgrpc.MyServer/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyServer_Handler1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Handler1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyServerServer).Handler1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tgrpc.MyServer/Handler1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyServerServer).Handler1(ctx, req.(*Handler1Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tgrpc.MyServer",
	HandlerType: (*MyServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _MyServer_Heartbeat_Handler,
		},
		{
			MethodName: "Handler1",
			Handler:    _MyServer_Handler1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
